baseURL = 'https://blogdarkspot.github.io/sample-blog/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'mini'

disqusShortname  = 'intelitrader-blog-sample-1'

[params]
    enableComments = true
